-- Subscription billing: auto-renew resume (deferred-dispatch cancellation). Design spec at
-- docs/superpowers/specs/2026-09-08-billing-auto-renew-resume-design.md. Razorpay's Subscriptions
-- API has no way to undo a dispatched cancel_at_cycle_end=true cancellation (verified directly
-- against Razorpay's own API docs -- see the design doc's "Why this can't be a thin wrapper on
-- Razorpay" section), so a real resume needs BillingCheckoutService.cancel() to stop calling
-- Razorpay immediately and defer that call to a background sweep instead.
--
-- NULL: either no cancellation is scheduled, or one is scheduled locally (auto_renew=false) but
-- not yet sent to Razorpay -- resume is a free, always-succeeding local flip in both cases.
-- Non-NULL: the real cancel_at_cycle_end=true call already reached Razorpay -- irreversible from
-- here, per Razorpay's own documented limitation.
ALTER TABLE subscriptions ADD COLUMN cancellation_dispatched_at TIMESTAMPTZ;
