/**
 * Turns a missing build artefact into a real 404, which Cloudflare Pages will not do on its own.
 *
 * <h2>What this fixes</h2>
 *
 * Pages answers a path that has no file with a DOCUMENT, and for a path under `/assets/` that is
 * always the wrong answer. Which document has changed; the handler covers both:
 *
 *  - While the build had no top-level `404.html`, it was the SPA fallback: `index.html`, `200`,
 *    `text/html`. A chunk deleted by a deploy came back as HTML with a success status, so a browser
 *    expecting JavaScript reported a MIME mismatch instead of "this file is gone", and every layer
 *    downstream had to infer the real cause from the wrong error. See
 *    `docs/investigations/incidents/2026-08-08-stale-chunk-login-failure.md`.
 *  - Now that the build has one (the not-found page, `scripts/prerender.mjs`), it is that page with
 *    a `404`. The status is right, but the body is still a whole HTML page handed to a script or
 *    stylesheet request. Measured on a Pages preview of that build before this handler knew about
 *    it: `/assets/<missing>.js` returned `404 text/html`, the not-found page.
 *
 * Either way the answer becomes a short plain-text `404`.
 *
 * <h2>Why a Function, when `_redirects` looks like it should do this</h2>
 *
 * It could not when this was written, and both dead ends are recorded because they look plausible
 * and cost a deploy each to disprove:
 *
 *  - `_redirects` needs a destination, so a 404 rule needs a `404.html` -- and adding that file
 *    REPLACES the SPA fallback, because Pages prefers `404.html` over `index.html` for unmatched
 *    paths. Every client route 404s. Measured on a preview: `/login`, `/about`, `/terms`,
 *    `/dashboard` all gone. (The build has a `404.html` today only because `public/_redirects` now
 *    rewrites every client route to a blank shell first.)
 *  - Repairing that with `/* /index.html 200` does not work either: Pages drops that rule. Its
 *    parser rejects a splat rewritten to `/index.html` as an infinite loop, since `/index.html`
 *    itself redirects to `/`. (An earlier version of this comment said Pages does not honour `200`
 *    rewrites at all. It does, to an extensionless path: `public/_redirects` relies on it.)
 *
 * A Function is the mechanism that can tell "no such asset" from "a route" without touching what
 * routes are served.
 *
 * <h2>Scope, and why it is safe</h2>
 *
 * `[[path]]` is a catch-all mounted at `/assets/` ONLY. Everything Vite emits there is a
 * content-hashed build artefact whose URL was generated by the build itself, so a request that
 * matches nothing always means "this file no longer exists" and never "this is a route". Nothing
 * outside `/assets/` reaches this handler, so client-side routing is untouched by construction --
 * which is precisely the property the `_redirects` attempts could not offer.
 *
 * <h2>Cost</h2>
 *
 * This adds a Worker invocation to asset requests that miss the browser and edge caches. Acceptable
 * here because `public/_headers` marks these responses `immutable, max-age=31536000`: a given
 * hashed URL is fetched once per client and then never revalidated, so the steady-state invocation
 * count is roughly "new assets x new visitors", not "every page view".
 */

/**
 * The one piece of the Pages Functions context this handler touches, declared locally rather than
 * depending on `@cloudflare/workers-types`.
 *
 * A whole types package to name a single zero-argument method is a poor trade, and it would be a
 * production dependency of the deployed Worker bundle for the sake of one annotation. `Request` and
 * `Response` come from the DOM lib the app already compiles against and are structurally identical
 * to the Workers runtime's.
 */
interface AssetRequestContext {
  /** Runs the rest of the Pages pipeline: the next Function if there is one, otherwise the static
   *  asset lookup -- which answers with a document when nothing matches. */
  next: () => Promise<Response>;
}

/**
 * True when a response under `/assets/` is a document standing in for a file that is not there:
 * the SPA fallback (`200`) or the build's not-found page (`404`).
 *
 * The test is the content type, because the status alone cannot tell: the fallback is a `200`, the
 * same as a real file. Under `/assets/` an HTML body can only be one of those two documents, since
 * Vite emits scripts, stylesheets, fonts and images there and never a document.
 *
 * Exported so the decision is unit-testable without a Workers runtime. This file is deployed
 * straight to the edge and is not covered by the app's build, so the test is the only thing
 * standing between a mistake here and every asset request in production.
 */
export function isDocumentForMissingAsset(response: Response): boolean {
  // Only the two statuses Pages gives those documents. A 304 carries no content type and must pass
  // through untouched -- it means the client already holds the file, the opposite of the file
  // being missing -- and a 5xx is an upstream failure that must stay visible as one.
  if (!response.ok && response.status !== 404) return false;

  const contentType = response.headers.get('content-type') ?? '';
  return contentType.toLowerCase().includes('text/html');
}

export async function onRequest(context: AssetRequestContext): Promise<Response> {
  const response = await context.next();

  if (!isDocumentForMissingAsset(response)) return response;

  // Deliberately `no-store`. A content-hashed name is never reused, so a 404 here is permanent in
  // principle -- but "permanent" assumes the deploy that should have published the file is
  // finished, and caching a miss recorded mid-propagation would outlive the condition that caused
  // it. The failure this exists to report is already rare and already self-heals on the client;
  // making it sticky at the edge would be the worse trade.
  return new Response('Not found\n', {
    status: 404,
    headers: {
      'content-type': 'text/plain; charset=utf-8',
      'cache-control': 'no-store',
    },
  });
}
